<?php
// database/seeders/MealKitSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\MealKit;
use App\Models\Category;

class MealKitSeeder extends Seeder
{
    public function run(): void
    {
        $traditionnel = Category::where('slug', 'plats-traditionnels')->firstOrFail()->id;
        $soupes       = Category::where('slug', 'soupes-sauces')->firstOrFail()->id;
        $grillades    = Category::where('slug', 'grillades')->firstOrFail()->id;
        $poissons     = Category::where('slug', 'poissons-fruits-de-mer')->firstOrFail()->id;
        $vegetarien   = Category::where('slug', 'vegetarien')->firstOrFail()->id;
        $petitdej     = Category::where('slug', 'petit-dejeuner')->firstOrFail()->id;
        $healthy      = Category::where('slug', 'healthy-fitness')->firstOrFail()->id;

        $kits = [

            // ── Plats traditionnels ───────────────────────────────

            [
                'category_id'   => $traditionnel,
                'name'          => 'Riz au poisson togolais',
                'description'   => 'Le plat emblématique de Lomé. Riz parfumé cuit dans un bouillon de poisson fumé, accompagné d\'une sauce tomate épicée au piment rouge et à l\'huile de palme.',
                'ingredients'   => "Riz local (500g), poisson fumé tilapia (300g), tomates fraîches (4), oignon rouge (2), ail (4 gousses), piment rouge (2), huile de palme (4 cuil.), sel, poivre, cube de bouillon",
                'images'        => json_encode(['https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800']),
                'prep_time'     => 45,
                'difficulty'    => 'easy',
                'calories'      => 580,
                'proteins'      => 32.0,
                'carbs'         => 72.0,
                'fats'          => 14.0,
                'fiber'         => 4.0,
                'price_1p'      => 4500.00,
                'price_2p'      => 8000.00,
                'price_4p'      => 14500.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.80,
                'rating_count'  => 124,
                'order_count'   => 312,
            ],
            [
                'category_id'   => $traditionnel,
                'name'          => 'Fufu de manioc et soupe de palme',
                'description'   => 'Le duo incontournable de la cuisine togolaise. Fufu lisse et élastique servi avec une soupe de palme riche en viande et légumes.',
                'ingredients'   => "Manioc frais (1kg), noix de palme (500g), mouton (400g), gombo (200g), feuilles de taro (150g), épinards (100g), piment, oignon, ail, sel",
                'images'        => json_encode(['https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800']),
                'prep_time'     => 75,
                'difficulty'    => 'medium',
                'calories'      => 720,
                'proteins'      => 28.0,
                'carbs'         => 95.0,
                'fats'          => 22.0,
                'fiber'         => 8.0,
                'price_1p'      => 5500.00,
                'price_2p'      => 10000.00,
                'price_4p'      => 18000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.90,
                'rating_count'  => 98,
                'order_count'   => 245,
            ],
            [
                'category_id'   => $traditionnel,
                'name'          => 'Akpan au lait de coco',
                'description'   => 'Bouillie de maïs fermenté onctueuse, enrichie au lait de coco et sucrée au sucre de canne. Petit-déjeuner ou dessert apprécié dans tout le Togo.',
                'ingredients'   => "Farine de maïs fermenté (200g), lait de coco (400ml), sucre de canne (3 cuil.), sel (pincée), eau (600ml)",
                'images'        => json_encode(['https://images.unsplash.com/photo-1571167366136-b57e0c89f0e8?w=800']),
                'prep_time'     => 25,
                'difficulty'    => 'easy',
                'calories'      => 340,
                'proteins'      => 6.0,
                'carbs'         => 58.0,
                'fats'          => 10.0,
                'fiber'         => 3.0,
                'price_1p'      => 2500.00,
                'price_2p'      => 4500.00,
                'price_4p'      => 8000.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.60,
                'rating_count'  => 67,
                'order_count'   => 178,
            ],
            [
                'category_id'   => $traditionnel,
                'name'          => 'Tô de sorgho et sauce arachide',
                'description'   => 'Pâte de sorgho dense et nourrissante accompagnée d\'une sauce arachide crémeuse avec de la viande de poulet fermier de Kpalimé.',
                'ingredients'   => "Farine de sorgho (300g), arachides grillées (200g), poulet fermier (500g), tomates (3), oignon (2), ail, gingembre, huile d'arachide, sel, piment",
                'images'        => json_encode(['https://images.unsplash.com/photo-1547592180-85f173990554?w=800']),
                'prep_time'     => 60,
                'difficulty'    => 'medium',
                'calories'      => 650,
                'proteins'      => 38.0,
                'carbs'         => 68.0,
                'fats'          => 24.0,
                'fiber'         => 6.0,
                'price_1p'      => 5000.00,
                'price_2p'      => 9000.00,
                'price_4p'      => 16500.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.70,
                'rating_count'  => 82,
                'order_count'   => 196,
            ],

            // ── Soupes & Sauces ───────────────────────────────────

            [
                'category_id'   => $soupes,
                'name'          => 'Sauce gombo au crabe',
                'description'   => 'Sauce gombo visqueuse et parfumée, préparée avec des crabes frais du golfe de Guinée, du poisson séché et des épices locales.',
                'ingredients'   => "Gombo frais (500g), crabes (4 pièces), poisson séché (150g), tomates (3), oignon (2), piment (2), huile de palme (3 cuil.), sel, cube de bouillon",
                'images'        => json_encode(['https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800']),
                'prep_time'     => 50,
                'difficulty'    => 'medium',
                'calories'      => 420,
                'proteins'      => 35.0,
                'carbs'         => 22.0,
                'fats'          => 18.0,
                'fiber'         => 9.0,
                'price_1p'      => 6000.00,
                'price_2p'      => 11000.00,
                'price_4p'      => 20000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.70,
                'rating_count'  => 73,
                'order_count'   => 167,
            ],
            [
                'category_id'   => $soupes,
                'name'          => 'Soupe de légumes au gingembre',
                'description'   => 'Bouillon léger et revitalisant de légumes frais du marché d\'Adawlato, parfumé au gingembre frais et à la citronnelle.',
                'ingredients'   => "Carottes (3), haricots verts (200g), aubergines africaines (4), tomates (3), gingembre frais (30g), citronnelle (2 tiges), oignon (1), ail (3 gousses), huile neutre, sel",
                'images'        => json_encode(['https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800']),
                'prep_time'     => 35,
                'difficulty'    => 'easy',
                'calories'      => 180,
                'proteins'      => 5.0,
                'carbs'         => 28.0,
                'fats'          => 6.0,
                'fiber'         => 7.0,
                'price_1p'      => 3000.00,
                'price_2p'      => 5500.00,
                'price_4p'      => 10000.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.40,
                'rating_count'  => 44,
                'order_count'   => 98,
            ],

            // ── Grillades ─────────────────────────────────────────

            [
                'category_id'   => $grillades,
                'name'          => 'Poulet braisé à l\'ivoirien',
                'description'   => 'Poulet entier mariné 12h dans un mélange d\'épices ouest-africaines, grillé lentement à la braise. Servi avec attiéké et sauce piment fraîche.',
                'ingredients'   => "Poulet entier (1.2kg), attiéké (400g), piment habanero (3), oignon (2), ail (6 gousses), gingembre (40g), citron vert (2), huile, sel, poivre, herbes fraîches",
                'images'        => json_encode(['https://images.unsplash.com/photo-1598103442097-8b74394b95c1?w=800']),
                'prep_time'     => 55,
                'difficulty'    => 'medium',
                'calories'      => 680,
                'proteins'      => 52.0,
                'carbs'         => 48.0,
                'fats'          => 26.0,
                'fiber'         => 3.0,
                'price_1p'      => 7500.00,
                'price_2p'      => 13500.00,
                'price_4p'      => 25000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.90,
                'rating_count'  => 156,
                'order_count'   => 389,
            ],
            [
                'category_id'   => $grillades,
                'name'          => 'Brochettes de bœuf épicées',
                'description'   => 'Cubes de bœuf local marinés dans une sauce épicée au piment de Cayenne et aux herbes. Grillés sur brochettes de bois de neem.',
                'ingredients'   => "Bœuf (500g), piment de Cayenne, paprika fumé, oignon, ail, gingembre, huile d'arachide, sel, persil, citron vert",
                'images'        => json_encode(['https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800']),
                'prep_time'     => 30,
                'difficulty'    => 'easy',
                'calories'      => 420,
                'proteins'      => 45.0,
                'carbs'         => 8.0,
                'fats'          => 22.0,
                'fiber'         => 1.0,
                'price_1p'      => 6500.00,
                'price_2p'      => 12000.00,
                'price_4p'      => 22000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.60,
                'rating_count'  => 88,
                'order_count'   => 201,
            ],

            // ── Poissons & Fruits de mer ──────────────────────────

            [
                'category_id'   => $poissons,
                'name'          => 'Tilapia grillé sauce tomate-gombo',
                'description'   => 'Tilapia entier du lac Togo, grillé et nappé d\'une sauce tomate-gombo onctueuse parfumée aux épices locales de Kpalimé.',
                'ingredients'   => "Tilapia entier (800g), gombo (200g), tomates (4), oignon (2), ail (4), piment (1), huile de palme, sel, citron, persil",
                'images'        => json_encode(['https://images.unsplash.com/photo-1532980400857-e8d9d275d858?w=800']),
                'prep_time'     => 40,
                'difficulty'    => 'easy',
                'calories'      => 380,
                'proteins'      => 42.0,
                'carbs'         => 15.0,
                'fats'          => 14.0,
                'fiber'         => 5.0,
                'price_1p'      => 5500.00,
                'price_2p'      => 10000.00,
                'price_4p'      => 18500.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.80,
                'rating_count'  => 112,
                'order_count'   => 278,
            ],
            [
                'category_id'   => $poissons,
                'name'          => 'Crevettes sautées à l\'ail et citron',
                'description'   => 'Grosses crevettes fraîches du golfe de Guinée sautées à vif dans un beurre d\'ail et de citron vert, servies sur riz vapeur.',
                'ingredients'   => "Crevettes fraîches (400g), beurre (50g), ail (6 gousses), citron vert (2), persil frais, piment doux, sel, poivre, riz parfumé (300g)",
                'images'        => json_encode(['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800']),
                'prep_time'     => 25,
                'difficulty'    => 'easy',
                'calories'      => 390,
                'proteins'      => 38.0,
                'carbs'         => 42.0,
                'fats'          => 10.0,
                'fiber'         => 1.0,
                'price_1p'      => 8000.00,
                'price_2p'      => 14500.00,
                'price_4p'      => 27000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.70,
                'rating_count'  => 64,
                'order_count'   => 143,
            ],

            // ── Végétarien ────────────────────────────────────────

            [
                'category_id'   => $vegetarien,
                'name'          => 'Haricots noirs épicés à la coco',
                'description'   => 'Haricots noirs locaux mijotés dans un lait de coco épicé avec des légumes du jardin. Riche en protéines végétales, servi avec du riz.',
                'ingredients'   => "Haricots noirs (300g), lait de coco (400ml), tomates (3), oignon (1), ail (3), gingembre, curcuma, piment doux, épinards (100g), riz (250g), sel",
                'images'        => json_encode(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800']),
                'prep_time'     => 55,
                'difficulty'    => 'easy',
                'calories'      => 480,
                'proteins'      => 22.0,
                'carbs'         => 68.0,
                'fats'          => 12.0,
                'fiber'         => 14.0,
                'price_1p'      => 3500.00,
                'price_2p'      => 6500.00,
                'price_4p'      => 12000.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.50,
                'rating_count'  => 52,
                'order_count'   => 124,
            ],
            [
                'category_id'   => $vegetarien,
                'name'          => 'Salade d\'igname et avocat',
                'description'   => 'Igname bouillie et avocat mûr de Kpalimé, assaisonnés d\'une vinaigrette à l\'huile d\'arachide et au citron. Frais et nourrissant.',
                'ingredients'   => "Igname blanche (600g), avocats mûrs (2), tomates cerises (200g), oignon rouge (1), citron vert (2), huile d'arachide (4 cuil.), sel, poivre, coriandre fraîche",
                'images'        => json_encode(['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800']),
                'prep_time'     => 30,
                'difficulty'    => 'easy',
                'calories'      => 390,
                'proteins'      => 8.0,
                'carbs'         => 52.0,
                'fats'          => 18.0,
                'fiber'         => 10.0,
                'price_1p'      => 4000.00,
                'price_2p'      => 7000.00,
                'price_4p'      => 13000.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.30,
                'rating_count'  => 38,
                'order_count'   => 89,
            ],

            // ── Petit-déjeuner ────────────────────────────────────

            [
                'category_id'   => $petitdej,
                'name'          => 'Bouillie de mil et arachides',
                'description'   => 'Bouillie onctueuse de mil jaune enrichie de pâte d\'arachide maison et sucrée au miel d\'acacia de Dapaong. Énergisante pour toute la matinée.',
                'ingredients'   => "Farine de mil (200g), pâte d'arachide (3 cuil.), miel d'acacia (2 cuil.), eau (800ml), sel (pincée), lait concentré non sucré (100ml)",
                'images'        => json_encode(['https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800']),
                'prep_time'     => 20,
                'difficulty'    => 'easy',
                'calories'      => 420,
                'proteins'      => 14.0,
                'carbs'         => 55.0,
                'fats'          => 16.0,
                'fiber'         => 5.0,
                'price_1p'      => 2000.00,
                'price_2p'      => 3500.00,
                'price_4p'      => 6500.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.60,
                'rating_count'  => 71,
                'order_count'   => 188,
            ],

            // ── Healthy & Fitness ─────────────────────────────────

            [
                'category_id'   => $healthy,
                'name'          => 'Bol de quinoa aux légumes du marché',
                'description'   => 'Quinoa protéiné garni de légumes colorés frais du marché d\'Adawlato, sauce tahini au citron. Idéal pour les sportifs et les personnes au régime.',
                'ingredients'   => "Quinoa (200g), carottes râpées (2), concombre (1), tomates cerises (150g), pois chiches (200g), épinards frais (80g), tahini (2 cuil.), citron (1), ail, sel, huile d'olive",
                'images'        => json_encode(['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800']),
                'prep_time'     => 25,
                'difficulty'    => 'easy',
                'calories'      => 450,
                'proteins'      => 20.0,
                'carbs'         => 58.0,
                'fats'          => 14.0,
                'fiber'         => 12.0,
                'price_1p'      => 5000.00,
                'price_2p'      => 9000.00,
                'price_4p'      => 16500.00,
                'is_vegetarian' => true,
                'is_active'     => true,
                'rating_avg'    => 4.50,
                'rating_count'  => 49,
                'order_count'   => 112,
            ],
            [
                'category_id'   => $healthy,
                'name'          => 'Blanc de poulet grillé aux herbes',
                'description'   => 'Filet de poulet fermier de Notsé grillé à l\'huile d\'olive et aux herbes, servi avec une salade de légumes croquants et du riz brun.',
                'ingredients'   => "Blanc de poulet (300g), riz brun (150g), haricots verts (200g), tomates (2), herbes de Provence, ail, huile d'olive (2 cuil.), citron, sel, poivre",
                'images'        => json_encode(['https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800']),
                'prep_time'     => 40,
                'difficulty'    => 'easy',
                'calories'      => 380,
                'proteins'      => 48.0,
                'carbs'         => 32.0,
                'fats'          => 8.0,
                'fiber'         => 5.0,
                'price_1p'      => 6000.00,
                'price_2p'      => 11000.00,
                'price_4p'      => 20000.00,
                'is_vegetarian' => false,
                'is_active'     => true,
                'rating_avg'    => 4.40,
                'rating_count'  => 57,
                'order_count'   => 134,
            ],
        ];

        foreach ($kits as $kit) {
            MealKit::create(array_merge($kit, [
                'slug' => Str::slug($kit['name']),
            ]));
        }
    }
}