<?php
// database/seeders/MealKitSeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use App\Models\{MealKit, Category};

class MealKitSeeder extends Seeder
{
    public function run(): void
    {
        $traditionnel  = Category::where('slug', 'plats-traditionnels')->first()->id;
        $soupes        = Category::where('slug', 'soupes-sauces')->first()->id;
        $grillades     = Category::where('slug', 'grillades')->first()->id;
        $poissons      = Category::where('slug', 'poissons-fruits-de-mer')->first()->id;
        $vegetarien    = Category::where('slug', 'vegetarien')->first()->id;
        $petitdej      = Category::where('slug', 'petit-dejeuner')->first()->id;
        $healthy       = Category::where('slug', 'healthy-fitness')->first()->id;

        $kits = [

            // ── Plats traditionnels ───────────────────────────────

            [
                'category_id'  => $traditionnel,
                'name'         => 'Riz au poisson togolais',
                'description'  => 'Le plat emblématique de Lomé. Riz parfumé cuit dans un bouillon de poisson fumé, accompagné d\'une sauce tomate épicée au piment rouge et à l\'huile de palme.',
                'ingredients'  => "Riz local (500g), poisson fumé (tilapia 300g), tomates fraîches (4), oignon rouge (2), ail (4 gousses), piment rouge (2), huile de palme (4 cuil.), sel, poivre, cube de bouillon",
                'instructions' => "1. Faire revenir l'oignon et l'ail dans l'huile de palme\n2. Ajouter les tomates et le piment mixés, laisser réduire 15 min\n3. Incorporer le poisson fumé effiloché et le bouillon\n4. Cuire le riz dans ce bouillon parfumé 20 min\n5. Servir avec la sauce tomate en accompagnement",
                'prep_time'    => 45,
                'difficulty'   => 'easy',
                'calories'     => 580,
                'proteins'     => 32,
                'carbs'        => 72,
                'fats'         => 14,
                'fiber'        => 4,
                'price_1p'     => 4500,
                'price_2p'     => 8000,
                'price_4p'     => 14500,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.8,
                'rating_count' => 124,
                'order_count'  => 312,
                'images'       => json_encode(['https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800']),
                'tags'         => json_encode(['populaire', 'traditionnel', 'poisson']),
            ],
            [
                'category_id'  => $traditionnel,
                'name'         => 'Fufu de manioc et soupe de palme',
                'description'  => 'Le duo incontournable de la cuisine togolaise. Fufu lisse et élastique servi avec une soupe de palme riche en viande et légumes.',
                'ingredients'  => "Manioc frais (1kg), noix de palme (500g), mouton (400g), gombo (200g), feuilles de taro (150g), épinards (100g), piment, oignon, ail, sel",
                'instructions' => "1. Peler et bouillir le manioc jusqu'à tendreté\n2. Piler le manioc chaud jusqu'à obtenir une pâte lisse\n3. Extraire le jus des noix de palme cuites\n4. Cuire la viande dans ce jus avec les légumes 30 min\n5. Former des boules de fufu et servir avec la soupe chaude",
                'prep_time'    => 75,
                'difficulty'   => 'medium',
                'calories'     => 720,
                'proteins'     => 28,
                'carbs'        => 95,
                'fats'         => 22,
                'fiber'        => 8,
                'price_1p'     => 5500,
                'price_2p'     => 10000,
                'price_4p'     => 18000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.9,
                'rating_count' => 98,
                'order_count'  => 245,
                'images'       => json_encode(['https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=800']),
                'tags'         => json_encode(['traditionnel', 'festif', 'famille']),
            ],
            [
                'category_id'  => $traditionnel,
                'name'         => 'Akpan au lait de coco',
                'description'  => 'Bouillie de maïs fermenté onctueuse, enrichie au lait de coco et sucrée au sucre de canne. Petit-déjeuner ou dessert apprécié dans tout le Togo.',
                'ingredients'  => "Farine de maïs fermenté (200g), lait de coco (400ml), sucre de canne (3 cuil.), sel (pincée), eau (600ml)",
                'instructions' => "1. Délayer la farine de maïs dans l'eau froide\n2. Porter à ébullition en remuant constamment\n3. Cuire à feu doux 15 min\n4. Incorporer le lait de coco et le sucre\n5. Remuer encore 5 min jusqu'à consistance crémeuse",
                'prep_time'    => 25,
                'difficulty'   => 'easy',
                'calories'     => 340,
                'proteins'     => 6,
                'carbs'        => 58,
                'fats'         => 10,
                'fiber'        => 3,
                'price_1p'     => 2500,
                'price_2p'     => 4500,
                'price_4p'     => 8000,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.6,
                'rating_count' => 67,
                'order_count'  => 178,
                'images'       => json_encode(['https://images.unsplash.com/photo-1571167366136-b57e0c89f0e8?w=800']),
                'tags'         => json_encode(['végétarien', 'petit-déjeuner', 'doux']),
            ],
            [
                'category_id'  => $traditionnel,
                'name'         => 'Tô de sorgho et sauce arachide',
                'description'  => 'Pâte de sorgho dense et nourrissante accompagnée d\'une sauce arachide crémeuse avec de la viande de poulet fermier de Kpalimé.',
                'ingredients'  => "Farine de sorgho (300g), arachides grillées (200g), poulet fermier (500g), tomates (3), oignon (2), ail, gingembre, huile d'arachide, sel, piment",
                'instructions' => "1. Préparer la pâte de sorgho en délayant la farine dans de l'eau bouillante\n2. Travailler vigoureusement jusqu'à consistance homogène\n3. Mixer les arachides avec les tomates\n4. Faire revenir le poulet, ajouter la pâte d'arachide\n5. Mijoter 25 min, servir avec le tô chaud",
                'prep_time'    => 60,
                'difficulty'   => 'medium',
                'calories'     => 650,
                'proteins'     => 38,
                'carbs'        => 68,
                'fats'         => 24,
                'fiber'        => 6,
                'price_1p'     => 5000,
                'price_2p'     => 9000,
                'price_4p'     => 16500,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.7,
                'rating_count' => 82,
                'order_count'  => 196,
                'images'       => json_encode(['https://images.unsplash.com/photo-1547592180-85f173990554?w=800']),
                'tags'         => json_encode(['traditionnel', 'poulet', 'arachide']),
            ],

            // ── Soupes & Sauces ───────────────────────────────────

            [
                'category_id'  => $soupes,
                'name'         => 'Sauce gombo au crabe',
                'description'  => 'Sauce gombo visqueuse et parfumée, préparée avec des crabes frais du golfe de Guinée, du poisson séché et des épices locales.',
                'ingredients'  => "Gombo frais (500g), crabes (4 pièces), poisson séché (150g), tomates (3), oignon (2), piment (2), huile de palme (3 cuil.), sel, cube de bouillon",
                'instructions' => "1. Mixer grossièrement le gombo\n2. Faire revenir l'oignon dans l'huile de palme\n3. Ajouter les tomates, le piment et laisser réduire\n4. Incorporer les crabes et le poisson séché\n5. Ajouter le gombo, cuire 20 min en remuant",
                'prep_time'    => 50,
                'difficulty'   => 'medium',
                'calories'     => 420,
                'proteins'     => 35,
                'carbs'        => 22,
                'fats'         => 18,
                'fiber'        => 9,
                'price_1p'     => 6000,
                'price_2p'     => 11000,
                'price_4p'     => 20000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.7,
                'rating_count' => 73,
                'order_count'  => 167,
                'images'       => json_encode(['https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800']),
                'tags'         => json_encode(['fruits de mer', 'crabe', 'épicé']),
            ],
            [
                'category_id'  => $soupes,
                'name'         => 'Soupe de légumes au gingembre',
                'description'  => 'Bouillon léger et revitalisant de légumes frais du marché d\'Adawlato, parfumé au gingembre frais et à la citronnelle.',
                'ingredients'  => "Carottes (3), haricots verts (200g), aubergines africaines (4), tomates (3), gingembre frais (30g), citronnelle (2 tiges), oignon (1), ail (3 gousses), huile neutre, sel",
                'instructions' => "1. Couper tous les légumes en morceaux réguliers\n2. Faire revenir l'oignon, l'ail et le gingembre\n3. Ajouter les légumes durs (carottes) en premier\n4. Incorporer progressivement les légumes tendres\n5. Ajouter la citronnelle et laisser infuser 10 min",
                'prep_time'    => 35,
                'difficulty'   => 'easy',
                'calories'     => 180,
                'proteins'     => 5,
                'carbs'        => 28,
                'fats'         => 6,
                'fiber'        => 7,
                'price_1p'     => 3000,
                'price_2p'     => 5500,
                'price_4p'     => 10000,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.4,
                'rating_count' => 44,
                'order_count'  => 98,
                'images'       => json_encode(['https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800']),
                'tags'         => json_encode(['végétarien', 'léger', 'détox']),
            ],

            // ── Grillades ─────────────────────────────────────────

            [
                'category_id'  => $grillades,
                'name'         => 'Poulet braisé à l\'ivoirien',
                'description'  => 'Poulet entier mariné 12h dans un mélange d\'épices ouest-africaines, grillé lentement à la braise. Servi avec attiéké et sauce piment fraîche.',
                'ingredients'  => "Poulet entier (1.2kg), attiéké (400g), piment habanero (3), oignon (2), ail (6 gousses), gingembre (40g), citron vert (2), huile, sel, poivre, herbes fraîches",
                'instructions' => "1. Mixer oignon, ail, gingembre, piment et citron\n2. Inciser le poulet profondément et le badigeonner de marinade\n3. Laisser mariner 12h minimum au réfrigérateur\n4. Griller à feu moyen 40-45 min en retournant régulièrement\n5. Servir avec l'attiéké et la sauce piment fraîche",
                'prep_time'    => 55,
                'difficulty'   => 'medium',
                'calories'     => 680,
                'proteins'     => 52,
                'carbs'        => 48,
                'fats'         => 26,
                'fiber'        => 3,
                'price_1p'     => 7500,
                'price_2p'     => 13500,
                'price_4p'     => 25000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.9,
                'rating_count' => 156,
                'order_count'  => 389,
                'images'       => json_encode(['https://images.unsplash.com/photo-1598103442097-8b74394b95c1?w=800']),
                'tags'         => json_encode(['populaire', 'poulet', 'braisé', 'attiéké']),
            ],
            [
                'category_id'  => $grillades,
                'name'         => 'Brochettes de bœuf épicées',
                'description'  => 'Cubes de bœuf local marinés dans une sauce épicée au piment de Cayenne et aux herbes. Grillés sur brochettes de bois de neem.',
                'ingredients'  => "Bœuf (500g), piment de Cayenne, paprika fumé, oignon, ail, gingembre, huile d'arachide, sel, persil, citron vert",
                'instructions' => "1. Couper le bœuf en cubes de 3cm\n2. Préparer la marinade épicée et enrober les cubes\n3. Laisser mariner 2h\n4. Enfiler sur les brochettes\n5. Griller 8-10 min en tournant régulièrement",
                'prep_time'    => 30,
                'difficulty'   => 'easy',
                'calories'     => 420,
                'proteins'     => 45,
                'carbs'        => 8,
                'fats'         => 22,
                'fiber'        => 1,
                'price_1p'     => 6500,
                'price_2p'     => 12000,
                'price_4p'     => 22000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.6,
                'rating_count' => 88,
                'order_count'  => 201,
                'images'       => json_encode(['https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800']),
                'tags'         => json_encode(['bœuf', 'brochette', 'épicé']),
            ],

            // ── Poissons & Fruits de mer ──────────────────────────

            [
                'category_id'  => $poissons,
                'name'         => 'Tilapia grillé sauce tomate-gombo',
                'description'  => 'Tilapia entier du lac Togo, grillé et nappé d\'une sauce tomate-gombo onctueuse parfumée aux épices locales de Kpalimé.',
                'ingredients'  => "Tilapia entier (800g), gombo (200g), tomates (4), oignon (2), ail (4), piment (1), huile de palme, sel, citron, persil",
                'instructions' => "1. Nettoyer et inciser le tilapia, saler et citronner\n2. Griller le tilapia 8 min de chaque côté\n3. Préparer la sauce : faire revenir oignon, ail, tomates\n4. Ajouter le gombo coupé fin et cuire 12 min\n5. Napper le poisson grillé de sauce chaude",
                'prep_time'    => 40,
                'difficulty'   => 'easy',
                'calories'     => 380,
                'proteins'     => 42,
                'carbs'        => 15,
                'fats'         => 14,
                'fiber'        => 5,
                'price_1p'     => 5500,
                'price_2p'     => 10000,
                'price_4p'     => 18500,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.8,
                'rating_count' => 112,
                'order_count'  => 278,
                'images'       => json_encode(['https://images.unsplash.com/photo-1532980400857-e8d9d275d858?w=800']),
                'tags'         => json_encode(['poisson', 'tilapia', 'local']),
            ],
            [
                'category_id'  => $poissons,
                'name'         => 'Crevettes sautées à l\'ail et citron',
                'description'  => 'Grosses crevettes fraîches du golfe de Guinée sautées à vif dans un beurre d\'ail et de citron vert, servies sur riz vapeur.',
                'ingredients'  => "Crevettes fraîches (400g), beurre (50g), ail (6 gousses), citron vert (2), persil frais, piment doux, sel, poivre, riz parfumé (300g)",
                'instructions' => "1. Décortiquer et déveiner les crevettes\n2. Faire fondre le beurre à feu vif\n3. Saisir les crevettes 2 min de chaque côté\n4. Ajouter l'ail écrasé, le jus de citron\n5. Finir au persil frais, servir sur riz vapeur",
                'prep_time'    => 25,
                'difficulty'   => 'easy',
                'calories'     => 390,
                'proteins'     => 38,
                'carbs'        => 42,
                'fats'         => 10,
                'fiber'        => 1,
                'price_1p'     => 8000,
                'price_2p'     => 14500,
                'price_4p'     => 27000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.7,
                'rating_count' => 64,
                'order_count'  => 143,
                'images'       => json_encode(['https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=800']),
                'tags'         => json_encode(['crevettes', 'fruits de mer', 'rapide']),
            ],

            // ── Végétarien ────────────────────────────────────────

            [
                'category_id'  => $vegetarien,
                'name'         => 'Haricots noirs épicés à la coco',
                'description'  => 'Haricots noirs locaux mijotés dans un lait de coco épicé avec des légumes du jardin. Riche en protéines végétales, servi avec du riz.',
                'ingredients'  => "Haricots noirs (300g), lait de coco (400ml), tomates (3), oignon (1), ail (3), gingembre, curcuma, piment doux, épinards (100g), riz (250g), sel",
                'instructions' => "1. Tremper les haricots 8h, égoutter et rincer\n2. Cuire les haricots 40 min\n3. Faire revenir oignon, ail, gingembre et épices\n4. Ajouter les haricots cuits et le lait de coco\n5. Mijoter 15 min, incorporer les épinards en fin de cuisson",
                'prep_time'    => 55,
                'difficulty'   => 'easy',
                'calories'     => 480,
                'proteins'     => 22,
                'carbs'        => 68,
                'fats'         => 12,
                'fiber'        => 14,
                'price_1p'     => 3500,
                'price_2p'     => 6500,
                'price_4p'     => 12000,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.5,
                'rating_count' => 52,
                'order_count'  => 124,
                'images'       => json_encode(['https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800']),
                'tags'         => json_encode(['végétarien', 'protéines', 'coco']),
            ],
            [
                'category_id'  => $vegetarien,
                'name'         => 'Salade d\'igname et avocat',
                'description'  => 'Igname bouillie et avocat mûr de Kpalimé, assaisonnés d\'une vinaigrette à l\'huile d\'arachide et au citron. Frais et nourrissant.',
                'ingredients'  => "Igname blanche (600g), avocats mûrs (2), tomates cerises (200g), oignon rouge (1), citron vert (2), huile d'arachide (4 cuil.), sel, poivre, coriandre fraîche",
                'instructions' => "1. Éplucher et cuire l'igname en cubes 20 min\n2. Laisser refroidir légèrement\n3. Couper les avocats et les tomates\n4. Préparer la vinaigrette citron-arachide\n5. Mélanger délicatement tous les éléments",
                'prep_time'    => 30,
                'difficulty'   => 'easy',
                'calories'     => 390,
                'proteins'     => 8,
                'carbs'        => 52,
                'fats'         => 18,
                'fiber'        => 10,
                'price_1p'     => 4000,
                'price_2p'     => 7000,
                'price_4p'     => 13000,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.3,
                'rating_count' => 38,
                'order_count'  => 89,
                'images'       => json_encode(['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800']),
                'tags'         => json_encode(['végétarien', 'salade', 'avocat']),
            ],

            // ── Petit-déjeuner ────────────────────────────────────

            [
                'category_id'  => $petitdej,
                'name'         => 'Bouillie de mil et arachides',
                'description'  => 'Bouillie onctueuse de mil jaune enrichie de pâte d\'arachide maison et sucrée au miel d\'acacia de Dapaong. Énergisante pour toute la matinée.',
                'ingredients'  => "Farine de mil (200g), pâte d'arachide (3 cuil.), miel d'acacia (2 cuil.), eau (800ml), sel (pincée), lait concentré non sucré (100ml)",
                'instructions' => "1. Délayer la farine dans un peu d'eau froide\n2. Porter le reste de l'eau à ébullition\n3. Verser le mélange en filet en remuant constamment\n4. Cuire 12 min à feu doux sans cesser de remuer\n5. Incorporer la pâte d'arachide, le miel et le lait",
                'prep_time'    => 20,
                'difficulty'   => 'easy',
                'calories'     => 420,
                'proteins'     => 14,
                'carbs'        => 55,
                'fats'         => 16,
                'fiber'        => 5,
                'price_1p'     => 2000,
                'price_2p'     => 3500,
                'price_4p'     => 6500,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.6,
                'rating_count' => 71,
                'order_count'  => 188,
                'images'       => json_encode(['https://images.unsplash.com/photo-1505253716362-afaea1d3d1af?w=800']),
                'tags'         => json_encode(['petit-déjeuner', 'végétarien', 'énergie']),
            ],

            // ── Healthy & Fitness ─────────────────────────────────

            [
                'category_id'  => $healthy,
                'name'         => 'Bol de quinoa aux légumes du marché',
                'description'  => 'Quinoa protéiné garni de légumes colorés frais du marché d\'Adawlato, sauce tahini au citron. Idéal pour les sportifs et les personnes au régime.',
                'ingredients'  => "Quinoa (200g), carottes râpées (2), concombre (1), tomates cerises (150g), pois chiches (200g), épinards frais (80g), tahini (2 cuil.), citron (1), ail, sel, huile d'olive",
                'instructions' => "1. Rincer et cuire le quinoa 15 min\n2. Préparer la sauce tahini au citron et à l'ail\n3. Rincer et égoutter les pois chiches\n4. Assembler le bol : quinoa + légumes + pois chiches\n5. Arroser de sauce tahini juste avant de servir",
                'prep_time'    => 25,
                'difficulty'   => 'easy',
                'calories'     => 450,
                'proteins'     => 20,
                'carbs'        => 58,
                'fats'         => 14,
                'fiber'        => 12,
                'price_1p'     => 5000,
                'price_2p'     => 9000,
                'price_4p'     => 16500,
                'is_vegetarian'=> true,
                'is_active'    => true,
                'rating_avg'   => 4.5,
                'rating_count' => 49,
                'order_count'  => 112,
                'images'       => json_encode(['https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800']),
                'tags'         => json_encode(['healthy', 'végétarien', 'fitness', 'quinoa']),
            ],
            [
                'category_id'  => $healthy,
                'name'         => 'Blanc de poulet grillé aux herbes',
                'description'  => 'Filet de poulet fermier de Notsé grillé à l\'huile d\'olive et aux herbes, servi avec une salade de légumes croquants et du riz brun.',
                'ingredients'  => "Blanc de poulet (300g), riz brun (150g), haricots verts (200g), tomates (2), herbes de Provence, ail, huile d'olive (2 cuil.), citron, sel, poivre",
                'instructions' => "1. Aplatir légèrement le filet de poulet\n2. Mariner 30 min avec ail, herbes, citron et huile\n3. Griller 6 min de chaque côté\n4. Cuire le riz brun 30 min\n5. Blanchir les haricots verts 4 min, servir aussitôt",
                'prep_time'    => 40,
                'difficulty'   => 'easy',
                'calories'     => 380,
                'proteins'     => 48,
                'carbs'        => 32,
                'fats'         => 8,
                'fiber'        => 5,
                'price_1p'     => 6000,
                'price_2p'     => 11000,
                'price_4p'     => 20000,
                'is_vegetarian'=> false,
                'is_active'    => true,
                'rating_avg'   => 4.4,
                'rating_count' => 57,
                'order_count'  => 134,
                'images'       => json_encode(['https://images.unsplash.com/photo-1532550907401-a500c9a57435?w=800']),
                'tags'         => json_encode(['healthy', 'poulet', 'fitness', 'faible calories']),
            ],
        ];

        foreach ($kits as $kit) {
            MealKit::create(array_merge($kit, [
                'slug' => Str::slug($kit['name']),
            ]));
        }
    }
}
